// <auto-generated />
using CobaMySql.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CobaMySql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CobaMySql.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Items that operate using electrical power or digital components.",
                            Name = "Electronics",
                            Slug = "electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Products related to clothing styles and accessories.",
                            Name = "Fashion",
                            Slug = "fashion"
                        });
                });

            modelBuilder.Entity("CobaMySql.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "This laptop integrates advanced AI capabilities to improve your workflow through real-time suggestions, personalized insights, and process automation.",
                            ImageUrl = "thinkpad-l16.webp",
                            Name = "ThinkPad L16 Gen 2 16 Inch AMD",
                            Price = 12000000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Perform with light textile upper and eva outsole for light feeling on easy sports activities",
                            ImageUrl = "diadora-piagio-black.webp",
                            Name = "Diadora Piagio Men's Running Shoes - Black",
                            Price = 4000000m,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("CobaMySql.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kevind@example.com",
                            FullName = "Kevind",
                            PasswordHash = "$2a$11$NmjwDAaZ97lHK3oNNMMQtekypyunVPOANB3jt69FGX0tgC5zUuGjq",
                            Username = "kevind"
                        },
                        new
                        {
                            Id = 2,
                            Email = "radhitya@example.com",
                            FullName = "Radhitya",
                            PasswordHash = "$2a$11$NmjwDAaZ97lHK3oNNMMQtekypyunVPOANB3jt69FGX0tgC5zUuGjq",
                            Username = "radhitya"
                        },
                        new
                        {
                            Id = 3,
                            Email = "wicaksono@example.com",
                            FullName = "Wicaksono",
                            PasswordHash = "$2a$11$NmjwDAaZ97lHK3oNNMMQtekypyunVPOANB3jt69FGX0tgC5zUuGjq",
                            Username = "wicaksono"
                        });
                });

            modelBuilder.Entity("CobaMySql.Models.Product", b =>
                {
                    b.HasOne("CobaMySql.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CobaMySql.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
